version: '2'
services:
    openai_server:
        image: registry.matreshkavpn.com:5000/openai_server
        restart: always
        container_name: 'openai_server'
        ports:
            - 8081:8081
        expose:
            - 8081

